### ISSUE TITLE
Upstream pruning

### ISSUE THREAD

**Issue by eldarkurtic** [IntelLabs/Model-Compression-Research-Package#1]
Hi!
First of all, thanks for open-sourcing your code for the "Prune Once for All" paper.
I would like to ask a few questions:
1. Are you planning to release your teacher model for upstream task? I have noticed that at https://huggingface.co/Intel , only the sparse checkpoints have been released. I would like to run some experiments with your compression package.
2.  From the published scripts, I have noticed that you have been using only English Wikipedia dataset for pruning at upstream tasks (MLM and NSP) but the `bert-base-uncased` model you use as a starting point is pre-trained on BookCorpus and English Wikipedia. Is there any specific reason why you haven't included BookCorpus dataset too?

**Comment by ofirzaf** [comment]
Hi,

Glad you found the paper interesting.

1. We don't plan to release the teachers we used. You can produce your own teacher using the training scripts in the examples with the default hyper-parameters published in original BERT paper or HuggingFace/transformers repo. We chose the best model out of 5 experiments with different seeds to be our teacher. Also, if you already have a trained model for the task you want to test or find one in the models hub, you can use it as well.
2. No special reason other than time. We started experimenting with only Wikipedia and we simply didn't have enough time to redo all the experiments with the addition of BookCorpus.
