### ISSUE TITLE
Sparse models available for download?

### ISSUE THREAD

**Issue by eldarkurtic** [IntelLabs/Model-Compression-Research-Package#15]
Hello :-)

I found your Prune-Once-For-All paper very interesting and would like to play with the sparse models that it produced. Are you going to open-source them soon? 

I have noticed you have open-sourced the sparse-pretrained models, but I couldn't find the corresponding models finetuned on downstream tasks (SQuAD, MNLI, QQP, etc.).

**Comment by ofirzaf** [comment]
We have open sourced some sparse models fine-tuned for SQuAD, available here:
https://huggingface.co/Intel/bert-base-uncased-squadv1.1-sparse-80-1x4-block-pruneofa
https://huggingface.co/Intel/bert-large-uncased-squadv1.1-sparse-80-1x4-block-pruneofa

It is also possible to create these models yourself using our model-compression-research-package without too much hassle.

Let me know if you can't find what you are looking for

**Comment by eldarkurtic** [comment]
Okay, thanks a lot for pointers.
