### ISSUE TITLE
Cannot import the package

### ISSUE THREAD

**Issue by g12bftd** [IntelLabs/Model-Compression-Research-Package#18]
I am trying to use your package as instructed in the README. I can successfully clone the repo.
When trying to "pip install -e ." (with or without square brackets), I get the following error message:

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Processing /content/Model-Compression-Research-Package
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Can you help with this issue?

**Comment by ofirzaf** [comment]
I'll take a look at it. Thanks for posting the issue.

**Comment by ofirzaf** [comment]
Fixed in #19, let me know if you are facing any other problems.
