### ISSUE TITLE
How to save QAT quantized model?

### ISSUE THREAD

**Issue by OctoberKat** [IntelLabs/Model-Compression-Research-Package#9]
Hi, thank you for your model compression package. I am a little confused about how to save QAT quantized model. Do you have an official website or documentation for this package?

**Comment by ofirzaf** [comment]
We dont have an official website or documentation. 

Regarding quantized models. At the moment we only have simulated quantization, meaning the tensors and computation are executed in FP32 but the values inside are quantized. We havn't implementated the mechanism to export a quantized model to any runtime.

Can you elaborate on what you are trying to do, maybe I could point you to some resources that might help you

**Comment by OctoberKat** [comment]
Thank you! I am exactly trying to export a quantized model to reduce the amount of data that is needed to be stored.

**Comment by ofirzaf** [comment]
If your only goal is to reduce model size then you can use a simpler process. Quantize only the weights of the model and save them in int8 format to reduce memory and when you load the weights, cast them back to fp32 for the inference process. This will, in most cases, not hurt the model accuracy. However, you won't get any inference speed up, only reduce model size.

Other than that, there are tools that already implemented the export process of a quantized model such as https://github.com/intel/neural-compressor
